config/routes.rb
ReceptenBoek::Application.routes.draw do
  devise_for :users
    devise_scope :user do
      authenticated :user do
          root 'recipes#index', as: :authenticated_root
      end

      unauthenticated do
        root 'static_pages#home', as: :unauthenticated_root
      end
      resource  :book
    end

  get '/recipes/:id/deactivate' => 'recipes#deactivate'
  get '/recipes/:id/activate'   => 'recipes#activate'
  get '/recipes/download/:id'   => 'recipes#download'
  get '/books/download_book'    => 'books#download_book'
  
  resources :recipes
  resources :books do
    post :update_row_order, on: :collection
  end
  
  resources :categories do
    post :update_row_order, on: :collection
  end
  
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  root :to => redirect("static_pages#home")

end

app/views/layouts/_footer.html.erb
<div class="footer">
  <p>Made by Tineke Willekes</p>
</div>

app/views/layouts/_header.html.erb
<header>
  <div class="navbar-wrapper">
    <div class="container">
      <nav class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <div class="navbar-brand"><%= link_to "recepten boek", root_path, id: "logo" %></div>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <% if signed_in? %>
                <li><%= link_to "Book", books_path %></li>
                <li><%= link_to "Recipes", recipes_path %></li>
                <li><%= link_to "Categories", categories_path %></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to "Profiel", edit_user_registration_path %></li>
                    <li><%= link_to "Book info", edit_book_path %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Sign out", destroy_user_session_path, method: "delete" %></li>
                  </ul>
                </li>
                
              <% else %>
                <li><%= link_to "Home",    root_path %></li>
                <li><%= link_to "About",   about_path %></li>
                <li><%= link_to "Contact", contact_path %></li>
                <li><%= link_to "Sign in", new_user_session_path %></li>
              <% end %>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_user_widget.html.erb
<% if user_signed_in? %>
  <p>Welcome <%= current_user.email %></p>
  <%= link_to 'Logged In [click to logout]', destroy_user_session_path, :method => :delete %>
<% else %>
  <p>You are not signed in.</p>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% if flash[:success] %>
      <div class="bg-success"><%= flash[:success] %></div>
    <% elsif flash[:alert] %>
      <div class="bg-danger"><%= flash[:alert] %></div>
    <% elsif notice %>
      <div class="bg-success"><%= notice %></div>
    <% else %>
    <% end %>
      
          <%= yield %>

    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/application.pdf.erb
<html>
  <head>
    <%= wicked_pdf_stylesheet_link_tag "pdf" %>
    <%= wicked_pdf_javascript_include_tag "http://code.jquery.com/jquery-1.10.0.min.js" %>
    <%= wicked_pdf_javascript_include_tag "http://code.jquery.com/ui/1.10.3/jquery-ui.min.js" %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/cover.pdf.erb
<h1><%= @book.title %></h1>
  <div class='book-image'>
  </div>
<h3 style='text-align:center;'>Written by <%= @book.author %></h3>
<h3 style='text-align:center;'>Year of publication <%= @book.year_of_publication %></h3>

app/views/layouts/footer.pdf.erb
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <%= wicked_pdf_javascript_include_tag "number_pages" %>
    <%= wicked_pdf_javascript_include_tag "http://code.jquery.com/jquery-1.10.0.min.js" %>
    <%= wicked_pdf_javascript_include_tag "http://code.jquery.com/ui/1.10.3/jquery-ui.min.js" %>
  </head>
 <body>
   <div id='footer_pdf'>
     <span class="page"></span>
   </div>
  </body>

</html>